import streamlit as st

# Acceder a las claves almacenadas en secrets.toml
PINECONE_API_KEY = st.secrets["pinecone"]["api_key"]
PINECONE_ENVIRONMENT_REGION = st.secrets["pinecone"]["environment_region"]
GROQ_API_KEY = st.secrets["groq"]["api_key"]

# Usar las claves como las usabas antes
print(PINECONE_API_KEY, PINECONE_ENVIRONMENT_REGION, GROQ_API_KEY)
